name: Build
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  windows:
    runs-on: windows-latest
    steps:
    - name: Check LongPathsEnabled
      run: |
          (Get-ItemProperty "HKLM:System\CurrentControlSet\Control\FileSystem").LongPathsEnabled
    - name: Checkout
      uses: actions/checkout@v2
    - name: Compile, Test and Validate
      run: Get-Location
    - name: Configure git and clone
      run: bash -lc "git config --global core.protectNTFS false; git clone -c core.longpaths=true https://github.com/clojerl/test.check"
    - name: Install Erlang
      run: choco install -y erlang --version 22.3
    - name: Install rebar3
      run: choco install -y rebar3 --version 3.13.1
    - name: Compile, Test and Validate
      run: bash -lc "make ci"
    - name: Compile Native
      run: bash -lc "make clean compile-native"
    - name: Generate Documentation
      run: bash -lc "make docs"
    - name: Publish Documentation
      uses: actions/upload-artifact@v1
      with:
        name: docs
        path: doc
