name: Build
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure git and clone
      run: git config --global core.protectNTFS false; git config --system core.longpaths true; git clone https://github.com/clojerl/test.check
    - name: Compile, Test and Validate
      run: bash -lc "echo foo"
    - name: Install Erlang
      run: choco install -y erlang --version 22.3
    - name: Install rebar3
      run: choco install -y rebar3 --version 3.13.1
    - name: Compile, Test and Validate
      run: bash -lc "make ci"
    - name: Compile Native
      run: bash -lc "make clean compile-native"
    - name: Generate Documentation
      run: bash -lc "make docs"
    - name: Publish Documentation
      uses: actions/upload-artifact@v1
      with:
        name: docs
        path: doc
