name: Build
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Check git
      run: git
    - name: Install Erlang
      run: choco install -y erlang --version 22.3
    - name: Install rebar3
      run: choco install -y rebar3 --version 3.13.1
    - name: Compile, Test and Validate
      run: make ci
    - name: Compile Native
      run: make clean compile-native
    - name: Generate Documentation
      run: make docs
    - name: Publish Documentation
      uses: actions/upload-artifact@v1
      with:
        name: docs
        path: doc
